import { Inter } from "next/font/google";
import "../../styles/globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import { ThemeProvider } from "@/components/theme-provider";
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
